✨ Add optional `permissions`-property to Alexa-`Card`
jovotech/jovo-output pull request #10
Opened 2021-08-02 14:49 UTC by m-ripper

Add optional `permission`-property to `Card` in `@jovotech/output-alexa`.
Also, define potential permission scopes but also supported custom permission scopes.

Personally, I am not sure whether we should call the `PermissionScope` to get the address `ReadAddressAll` (current state) or rename it to `ReadAddress`.

2021-08-02 15:08 UTC, aswetlow commented on output-alexa/src/models/card/Card.ts
> +  ReadAddressAll = 'read::alexa:device:all:address',
What about `ReadAddressFull`?

2021-08-03 08:49 UTC, aswetlow requested changes

2021-08-03 08:49 UTC, aswetlow commented on output-alexa/src/models/card/Card.ts
> +  ReadAddressAll = 'read::alexa:device:all:address',
https://developer.amazon.com/en-US/docs/alexa/custom-skills/device-address-api.html#getAddress

"Gets the full address associated with the device specified by deviceId."

I think `ReadAddressFull` is reasonable.

2021-08-03 12:01 UTC, aswetlow approved these changes

2021-08-09 11:16 UTC, jankoenig approved these changes

2021-08-09 11:23 UTC, merged